on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Printing folder contents Befor'
        run: ls

      - uses: actions/checkout@v3
      
      - name: 'Printing folder contents After'
        run: ls
      