on:
  push:
    - master



jops:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing github action'
        run: pwd 
      
      - name: 'Testing printing'
        run: echo abdelsamea
